#! /usr/bin/env perl
use utf8;
use strict;
use warnings;

use WebService::Qiita::CLI;

&main;exit;

sub main {
    my $cli = WebService::Qiita::CLI->new;
    $cli->parse_options;
    $cli->run;
}
__END__

=head1 NAME

qiita - command line interface for Qiita

=head1 SYNOPSIS

    $ qiita [--version] [--help] <command> [<args>]

Commands:

=head1 DESCRIPTION

This is a command line interface for Qiita API.

The qiita command provides you with easy accessing qiita items and users.

=head1 AUTHOR

Yuuki Tsubouchi <yuuki@cpan.org>

=cut
